# -*- coding: utf-8 -*-
"""DAY1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT5B4Sx92uiB3JUL-1Bv4bj2qUMTZ8X9
"""

print('hello,world')
print('Manjushree')
print('computer science engineering')

prin("i am your student")

print("i am your student") # Changed 'prin' to 'print'

print("nbgkbj")
""""hbth"""

x=10
print(x)
y=3.14
print(y,name)
name="john"
print(name)
print(name + ' is a teacher')
print(x,y,name)

name=input("enter student name")
a=input("enter a number")
print(name)

a=int(input("enter a number "))
b=int(input("enter a number "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

r=float(input("enter the value of radius "))
pi=3.14
area = pi*r*r
print(area)

celsius=float(input("enter tempeature in celsius "))
fahrenheit=(celsius*9/5)+32
print("temperature in fahrenheit" , fahrenheit)